// <auto-generated />
using System;
using EPAD_Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EPAD_Data.Migrations.Sync_
{
    [DbContext(typeof(Sync_Context))]
    partial class Sync_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EPAD_Data.Entities.IC_BussinessTravel_Integrate_AVN", b =>
                {
                    b.Property<long>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BusinessTravelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BusinessTripType")
                        .HasColumnType("int");

                    b.Property<string>("CodeAttendance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeEmp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime2");

                    b.Property<string>("DurationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IntegrateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlaceFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceTo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Index");

                    b.ToTable("IC_BussinessTravel_Integrate_AVN");
                });

            modelBuilder.Entity("EPAD_Data.Entities.IC_Department_Integrate_AVN", b =>
                {
                    b.Property<long>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("IntegrateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrgStructureName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Index");

                    b.ToTable("IC_Department_Integrate_AVN");
                });

            modelBuilder.Entity("EPAD_Data.Entities.IC_Department_Integrate_OVN", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrgUnitID")
                        .HasColumnType("int");

                    b.Property<int>("ParentNodeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("IC_Department_Integrate_OVN");
                });

            modelBuilder.Entity("EPAD_Data.Entities.IC_EmployeeShift_Integrate_AVN", b =>
                {
                    b.Property<long>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodeEmp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IntegrateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShiftCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShiftName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Index");

                    b.ToTable("IC_EmployeeShift_Integrate_AVN");
                });

            modelBuilder.Entity("EPAD_Data.Entities.IC_Employee_Integrate", b =>
                {
                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeATID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrgUnitID")
                        .HasColumnType("int");

                    b.Property<int?>("OrgUnitParentNode")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StoppedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Index")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.ToTable("IC_Employee_Integrate");
                });

            modelBuilder.Entity("EPAD_Data.Entities.IC_Employee_Integrate_AVN", b =>
                {
                    b.Property<long>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodeAttendance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeEmp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateQuit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IntegrateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrgStructureCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusSyn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("datecreate")
                        .HasColumnType("datetime2");

                    b.HasKey("Index");

                    b.ToTable("IC_Employee_Integrate_AVN");
                });

            modelBuilder.Entity("EPAD_Data.Entities.IC_Employee_Shift_Integrate", b =>
                {
                    b.Property<long>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ShiftApplyDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ShiftFromTime")
                        .HasColumnType("datetime");

                    b.Property<string>("ShiftName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShiftToTime")
                        .HasColumnType("datetime");

                    b.HasKey("Index")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.ToTable("IC_Employee_Shift_Integrate");
                });

            modelBuilder.Entity("EPAD_Data.Entities.IC_OverTimePlan_Integrate_AVN", b =>
                {
                    b.Property<long>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodeAttendance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeEmp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IntegrateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeTo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WorkDateRoot")
                        .HasColumnType("datetime2");

                    b.HasKey("Index");

                    b.ToTable("IC_OverTimePlan_Integrate_AVN");
                });

            modelBuilder.Entity("EPAD_Data.Entities.IC_Position_Integrate_AVN", b =>
                {
                    b.Property<long>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IntegrateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PositionEngName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Index");

                    b.ToTable("IC_Position_Integrate_AVN");
                });

            modelBuilder.Entity("EPAD_Data.Entities.IC_Shift_Integrate_AVN", b =>
                {
                    b.Property<long>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CoOut")
                        .HasColumnType("float");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IntegrateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OutTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShiftName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Index");

                    b.ToTable("IC_Shift_Integrate_AVN");
                });
#pragma warning restore 612, 618
        }
    }
}
